- id: add-hooks
  name: add-hooks
  entry: add-hooks
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml
  description: Add hooks
- id: check-version-bumped
  name: check-version-bumped
  entry: check-version-bumped
  language: python
  always_run: true
  pass_filenames: false
  description: Check version bumped
- id: format-requirements
  name: format-requirements
  entry: format-requirements
  language: python
  types: [toml]
  files: pyproject\.toml
  description: Format requirements
- id: replace-sequence-str
  name: replace-sequence-str
  entry: replace-sequence-str
  language: python
  types: [python]
  description: Replace `Sequence[str]` with `list[str]`
- id: run-bump-my-version
  name: run-bump-my-version
  entry: run-bump-my-version
  language: python
  always_run: true
  pass_filenames: false
  description: Run `bump-my-version`
