- id: elm
  name: Elm
  entry: elm-format
  language: node
  files: \.elm$
  types: [text]
  args: [--yes]
  additional_dependencies: ["elm-format@0.8.4"]

- id: markdown
  name: Markdown
  entry: markdownlint-cli2
  language: node
  types: [markdown]
  additional_dependencies: ["markdownlint-cli2@0.0.13"]

- id: no-binary
  name: No binary
  entry: hooks/jumanjihouse/pre_commit_hooks/no_binary
  language: script
  types: [binary]

- id: no-commit
  name: No commit
  entry: no-commit
  language: python
  pass_filenames: false
  always_run: true

- id: notebook
  name: Notebooks
  entry: notebook
  language: python
  types: [jupyter]

- id: prettier
  name: Prettier
  entry: prettier
  language: node
  types: [text]
  args: [--ignore-unknown, --list-different, --write]
  additional_dependencies: ["prettier@2.2.1"]

- id: python
  name: Python
  entry: do-python
  language: python
  types: [python]

- id: shell-exec
  name: Shell (executable)
  entry: hooks/jumanjihouse/pre_commit_hooks/script_must_not_have_extension
  language: script
  types: [shell, executable]

- id: shell-non-exec
  name: Shell (non-executable)
  entry: hooks/jumanjihouse/pre_commit_hooks/script_must_have_extension
  language: script
  types: [shell, non-executable]

- id: shellcheck
  name: Shell (shellcheck)
  entry: shellcheck
  language: conda
  types: [shell]
  additional_dependencies: ["--channel", "conda-forge", "shellcheck"]

- id: shfmt
  name: Shell (shfmt)
  entry: shfmt
  language: conda
  types: [shell]
  args: [-w]
  additional_dependencies: ["--channel", "conda-forge", "go-shfmt"]

- id: text
  name: Text
  entry: text
  language: python
  types: [text]

- id: universal
  name: Universal
  entry: universal
  language: python
