- id: check-submodules-updated
  name: check-submodules-updated
  entry: check-submodules-updated
  language: python
  always_run: true
  pass_filenames: false
  description: Check submodules updated
  stages: [pre-push]
- id: check-version-bumped
  name: check-version-bumped
  entry: check-version-bumped
  language: python
  always_run: true
  pass_filenames: false
  description: Check version bumped
- id: format-requirements
  name: format-requirements
  entry: format-requirements
  language: python
  types: [toml]
  files: pyproject\.toml
  description: Format requirements
- id: replace-sequence-str
  name: replace-sequence-str
  entry: replace-sequence-str
  language: python
  types: [python]
  description: Replace `Sequence[str]` with `list[str]`
- id: mirror-files
  name: mirror-files
  entry: mirror-files
  language: python
  always_run: true
  pass_filenames: false
  description: Mirror files
- id: run-bump-my-version
  name: run-bump-my-version
  entry: run-bump-my-version
  language: python
  always_run: true
  pass_filenames: false
  description: Run `bump-my-version`
- id: tag-commits
  name: tag-commits
  entry: tag-commits
  language: python
  always_run: true
  pass_filenames: false
  description: Tag commits
