- id: add-future-import-annotations
  name: add-future-import-annotations
  entry: add-future-import-annotations
  language: python
  types: [python]

- id: add-hooks
  name: add-hooks
  entry: add-hooks
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: add-ruff-hooks
  name: add-ruff-hooks
  entry: add-ruff-hooks
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: check-versions-consistent
  name: check-versions-consistent
  entry: check-versions-consistent
  language: python
  types: [toml]
  files: \.bumpversion\.toml

- id: format-requirements
  name: format-requirements
  entry: format-requirements
  language: python
  types: [toml]
  files: pyproject\.toml

- id: replace-sequence-str
  name: replace-sequence-str
  entry: replace-sequence-str
  language: python
  types: [python]

- id: run-version-bump
  name: run-version-bump
  entry: run-version-bump
  language: python
  types: [toml]
  files: \.bumpversion\.toml

- id: update-requirements
  name: update-requirements
  entry: update-requirements
  language: python
  types: [toml]
  files: pyproject\.toml

  ##

- id: check-version-bumped
  name: check-version-bumped
  entry: check-version-bumped
  language: python
  always_run: true
  pass_filenames: false
