- id: elm
  name: Elm
  entry: elm-format
  language: node
  files: \.elm$
  types: [text]
  args: [--yes]
  additional_dependencies: ["elm-format@0.8.4"]

- id: no-commit
  name: No commit
  entry: no-commit
  language: python
  pass_filenames: false
  always_run: true

- id: prettier
  name: Prettier
  entry: prettier
  language: node
  types: [text]
  args: [--ignore-unknown, --list-different, --write]
  additional_dependencies: ["prettier@2.2.1"]

- id: python
  name: Python
  entry: do-python
  language: python
  types: [python]

- id: shellcheck
  name: Shellcheck
  entry: shellcheck
  language: conda
  types: [shell]

- id: shfmt
  name: Shfmt
  entry: shfmt
  language: conda
  types: [shell]
  args: [-w]

- id: text
  name: Text
  entry: text
  language: python
  types: [text]

- id: universal
  name: Universal
  entry: universal
  language: python
