- id: replace-sequence-str
  name: replace-sequence-str
  entry: replace-sequence-str
  language: python
  types: [python]
  description: Replace `Sequence[str]` with `list[str]`
- id: run-bump-my-version
  name: run-bump-my-version
  entry: run-bump-my-version
  language: python
  always_run: true
  pass_filenames: false
  description: Run `bump-my-version`
- id: run-ruff-format
  name: run-ruff-format
  entry: run-ruff-format
  language: python
  always_run: true
  pass_filenames: false
  description: Run `ruff format`
- id: test-hook
  name: test-hook
  entry: run-uv-pip-compile
  language: python
  files: ^pyproject\.toml$
  pass_filenames: false
  description: Run `uv pip compile`
  args: [
      # --output-file=requirements-macos.txt,
      # --extra=interactive,
      # --python-platform=macos,
      # --python-version=3.12,
      --output-file=requirements-linux.txt,
      --python-platform=linux,
      --python-version=3.12,
    ]
