- id: add-future-import-annotations
  name: add-future-import-annotations
  entry: add-future-import-annotations
  language: python
  types: [python]

- id: add-hooks
  name: add-hooks
  entry: add-hooks
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: check-versions-consistent
  name: check-versions-consistent
  entry: check-versions-consistent
  language: python
  types: [toml]
  files: \.bumpversion\.toml

- id: format-pre-commit-config
  name: format-pre-commit-config
  entry: format-pre-commit-config
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: format-requirements
  name: format-requirements
  entry: format-requirements
  language: python
  types: [toml]
  files: pyproject\.toml

- id: replace-sequence-str
  name: replace-sequence-str
  entry: replace-sequence-str
  language: python
  types: [python]

- id: run-prek-autoupdate
  name: run-prek-autoupdate
  entry: run-prek-autoupdate
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: run-version-bump
  name: run-version-bump
  entry: run-version-bump
  language: python
  types: [toml]
  files: \.bumpversion\.toml

- id: setup-git
  name: setup-git
  entry: setup-git
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: setup-pyright
  name: setup-pyright
  entry: setup-pyright
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: setup-ruff
  name: setup-ruff
  entry: setup-ruff
  language: python
  types: [yaml]
  files: \.pre-commit-config\.yaml

- id: update-requirements
  name: update-requirements
  entry: update-requirements
  language: python
  types: [toml]
  files: pyproject\.toml

- id: update-requirements
  name: update-requirements
  entry: update-requirements
  language: python
  types: [toml]
  files: pyproject\.toml

##

- id: check-version-bumped
  name: check-version-bumped
  entry: check-version-bumped
  language: python
  always_run: true
  pass_filenames: false
