#!/usr/bin/env bash

here=$(readlink -f "$0")
here=$(dirname "$here")
target="$here/.git/hooks/pre-commit"

if [ -f "$target" ]; then
	printf "Pre-commit hooks are already installed at:\n    %s\n" "$target"
	echo For now we overwrite...
	source="$here/pre-commit"
	cp "$source" "$target"
else
	printf "Installing pre-commit hooks at:\n    %s\n" "$target"
	source="$here/pre-commit"
	cp "$source" "$target"
fi
