#!/usr/bin/env bash

path_here="$(dirname "$(readlink -f "$0")")"
path_target="$path_here/.git/hooks/pre-commit"

if [ -f "$path_target" ]; then
	printf "Pre-commit hooks are already installed at:\n    %s\n" "$path_target"
	echo For now we overwrite...
	path_source="$path_here/pre-commit"
	cp "$path_source" "$path_target"
else
	printf "Installing pre-commit hooks at:\n    %s\n" "$path_target"
	path_source="$path_here/pre-commit"
	cp "$path_source" "$path_target"
fi
