#!/usr/bin/env bash
# shellcheck source=/dev/null

run_hooks_on_all_files() {
	if [ -z "$(git diff --name-only --cached)" ]; then
		return 0
	fi

	root=$(git rev-parse --show-toplevel)
	code=0
	while read -r staged_file; do
		path_staged="$root/$staged_file"
		if [ -f "$path_staged" ]; then
			if ! run_hooks_on_file_path "$path_staged"; then
				code=1
			fi
		elif [ -d "$path_staged" ]; then
			while read -r file_staged; do
				if ! run_hooks_on_file_path "$root/$file_staged"; then
					code=1
				fi
			done <<<"$(git ls-files "$path_staged")"
		fi
	done <<<"$(git diff --name-only --cached)"

	if [ -n "$(git diff --name-only --cached)" ]; then
		return $code
	else
		return 0
	fi
}

run_hooks_on_file_path() {
	root=$(git rev-parse --show-toplevel)
	if [ -d "$root/.pre-commit-hooks" ]; then
		path="$root/.pre-commit-hooks" # deployment
	else
		path="$root" # development
	fi
	code=0
	while read -r hook; do
		if ! "$hook" "$1"; then
			code=1
		fi
	done <<<"$(find "$path/hooks" -type f)"
	return $code
}

if run_hooks_on_all_files; then
	exit 0
else
	exit 1
fi
