#!/usr/bin/env bash

path_here="$(dirname "$(readlink -f "$0")")"
path_target="$path_here/.git/hooks/pre-commit"

if [ -f "$path_target" ]; then
	printf "Uninstalling pre-commit hooks from:\n    %s\n" "$path_target"
	rm "$path_target"
else
	printf "No pre-commit hooks are currently installed at:\n    %s\n" "$path_target"
fi
