#!/usr/bin/env bash

fail_if_missing_and_strict() {
	if command -v "$1" >/dev/null 2>&1; then
		return 0
	else
		if [[ -n $PRE_COMMIT_STRICT ]]; then
			if [[ -n "$PRE_COMMIT_DEBUG" ]]; then
				printf "FAILING: \"%s\" not found\n" "$1"
			fi
			return 1
		else
			if [[ -n "$PRE_COMMIT_DEBUG" ]]; then
				printf "SKIPPING: \"%s\" not found\n" "$1"
			fi
			return 0
		fi
	fi

}

if fail_if_missing_and_strict "$1"; then
	exit 0
else
	exit 1
fi
