#!/usr/bin/env bash

is_bash_file() {
	if ! [ -f "$1" ]; then return 1; fi
	if [[ "$1" == *.bash ]]; then
		return 0
	fi
	line=$(head -n 1 "$1")
	if [[ "$line" == *bash* ]]; then
		return 0
	else
		return 1
	fi
}

if is_bash_file "$1"; then
	exit 0
else
	exit 1
fi
