#!/usr/bin/env bash

process_file() {
	if ! is_bash_file "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "check_shell skipped %s\n" "$1"
		return 0
	fi
	if ! command -v shfmt >/dev/null 2>&1; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt missing\n"
		return 1
	fi
	if ! shfmt -w "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt failed on %s\n" "$1"
		return 1
	fi
	git add "$1"
	if ! command -v shellcheck >/dev/null 2>&1; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shellcheck missing\n"
		return 1
	fi
	shellcheck "$1"
	return $?
}

is_bash_file() {
	if [[ "$1" == *.bash ]]; then
		return 0
	fi
	line=$(head -n 1 "$1")
	if [[ "$line" == *bash* ]]; then
		return 0
	else
		return 1
	fi
}

process_file "$1"
exit $?
