#!/usr/bin/env bash

process_files() {
	code=0
	for file in "$@"; do
		if is_bash_file "$file"; then
			if ! process_file "$file"; then
				code=1
			fi
		else
			[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "SKIP: check_shell skipped %s\n" "$file"
		fi
	done
	return $code
}

is_bash_file() {
	if ! [ -f "$1" ]; then
		return 1
	fi
	if [[ "$1" == *.bash ]]; then
		return 0
	fi
	line=$(head -n 1 "$1")
	if [[ "$line" == *bash* ]]; then
		return 0
	else
		return 1
	fi
}

process_file() {
	if ! command -v shfmt >/dev/null 2>&1; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt missing\n"
		return 1
	fi
	if ! shfmt -w "$file"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shfmt failed on %s\n" "$file"
	fi
	git add "$file"
	if ! command -v shellcheck >/dev/null 2>&1; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: shellcheck missing\n"
		return 1
	fi
	shellcheck "$file"
	return $?
}

process_files "$@"
exit $?
