#!/usr/bin/env bash

process_file() {
	if ! is_python_file "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "check_python skipped %s\n" "$1"
		return 0
	fi

	# formatters
	## black
	if ! command -v black >/dev/null 2>&1; then
		printf "ERROR: black missing\n"
		return 1
	fi
	if ! black "$1" --quiet; then
		printf "ERROR: black failed on %s\n" "$1"
		return 1
	fi

	## add-trailing-comma
	if ! command -v add-trailing-comma >/dev/null 2>&1; then
		printf "ERROR: add-trailing-comma missing\n"
		return 1
	fi
	if ! add-trailing-comma "$1" --exit-zero-even-if-changed --py36-plus; then
		printf "ERROR: failed on %s\n" "$1"
	fi
	if ! black "$1" --quiet; then
		printf "ERROR: black (after add-trailing-comma) failed on %s\n" "$1"
		return 1
	fi

	## autoflake
	if ! command -v autoflake >/dev/null 2>&1; then
		printf "ERROR: autoflake missing\n"
		return 1
	fi
	autoflake --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables "$1"
	if ! black "$1" --quiet; then
		printf "ERROR: black (after autoflake) failed on %s\n" "$1"
		return 1
	fi

	## pyupgrade
	if ! command -v pyupgrade >/dev/null 2>&1; then
		printf "ERROR: pyupgrade missing\n"
		return 1
	fi
	if ! pyupgrade --exit-zero-even-if-changed --py38-plus "$1"; then
		printf "ERROR: pyupgrade failed on %s\n" "$1"
	fi
	if ! black "$1" --quiet; then
		printf "ERROR: black (after pyupgrade) failed on %s\n" "$1"
		return 1
	fi

	## yesqa
	if ! command -v yesqa >/dev/null 2>&1; then
		printf "ERROR: yesqa missing\n"
		return 1
	fi
	if ! yesqa "$1"; then
		printf "ERROR: yesqa failed on %s\n" "$1"
	fi
	if ! black "$1" --quiet; then
		printf "ERROR: black (after yesqa) failed on %s\n" "$1"
		return 1
	fi

	git add "$1"

	# linters
	## flake8
	if ! command -v flake8 >/dev/null 2>&1; then
		printf "ERROR: flake8 missing\n"
		return 1
	fi
	path_ignores="$(dirname "$(dirname "${BASH_SOURCE[0]}")")/python/flake8-ignores"
	declare -a all_ignores
	while read -r line; do
		if [ -n "$line" ] && ! [[ "$line" == \#* ]]; then
			all_ignores+=("$line")
		fi
	done <"$path_ignores"
	ignore=$(printf ",%s" "${all_ignores[@]}")
	ignore=${ignore:1}
	if ! flake8 --ignore="$ignore" --per-file-ignores="tests/*.py:S101" "$1"; then
		printf "ERROR: flake8 failed on %s\n" "$1"
		return 1
	fi
	return 0
}

is_python_file() {
	if [[ -f "$1" ]] && [[ "$1" == *.py ]]; then
		return 0
	else
		return 1
	fi
}

process_file "$1"
exit $?
