#!/usr/bin/env bash

process_file() {
	if ! is_python_file "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "check_python skipped %s\n" "$1"
		return 0
	fi
	if ! command -v black >/dev/null 2>&1; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: black missing\n"
		return 1
	fi
	if black "$1"; then
		git add "$1"
	else
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "ERROR: black failed on %s\n" "$1"
		return 1
	fi
	return 0
}

is_python_file() {
	if [[ -f "$1" ]] && [[ "$1" == *.py ]]; then
		return 0
	else
		return 1
	fi
}

process_file "$1"
exit $?
