#!/usr/bin/env bash

process_file() {
	if ! [[ "$1" =~ \.elm$ ]]; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "elm_hooks skipped %s\n" "$1"
		return 0
	fi
	if ! command -v elm-format >/dev/null 2>&1; then
		printf "ERROR: elm-format missing\n"
		return 1
	fi
	if ! elm-format "$1" --yes >/dev/null 2>&1; then
		printf "ERROR: elm-format failed on %s\n" "$1"
	fi
	git add "$1"
	return 0
}

process_file "$@"
exit $?
