#!/usr/bin/env bash

process_file() {
	if ! [[ "$1" =~ \.(html|js|json|md|tomj|ts|xml)$ ]]; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "prettier skipped %s\n" "$1"
		return 0
	fi

	# fixers
	if ! command -v npx >/dev/null 2>&1; then
		printf "ERROR: npx missing\n"
		return 1
	fi
	if ! npx prettier --write "$1"; then
		printf "ERROR: prettier failed on %s\n" "$1"
		return 1
	fi

	# fixers - end
	git add "$1"

	return 0
}

process_file "$1"
exit $?
