#!/usr/bin/env bash

process_file() {
	if ! is_accepted_file "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "prettier skipped %s\n" "$1"
		return 0
	fi

	# fixers
	# if ! command -v shfmt >/dev/null 2>&1; then
	# 	printf "ERROR: shfmt missing\n"
	# 	return 1
	# fi
	# if ! shfmt -w "$1"; then
	# 	printf "ERROR: shfmt failed on %s\n" "$1"
	# 	return 1
	# fi

	# fixers - end
	git add "$1"

	echo "$1..."

	return 0
}

is_accepted_file() {
	if [[ -f "$1" ]] && [[ "$1" =~ \.(html|js|md|ts)$ ]]; then
		return 0
	else
		return 1
	fi
}

process_file "$1"
exit $?
