#!/usr/bin/env bash
set -eu

################################################################################
# Ensure shell scripts conform to style guide.
################################################################################

readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
	set -x
fi

here="$(dirname "$0")"
hooks_dir="$here/jumanjihouse/pre_commit_hooks"
declare -a hooks=()
hooks+=("script_must_have_extension")
hooks+=("script_must_not_have_extension")
for hook in "${hooks[@]}"; do
	echo zzzzzzzz "$hook"
	readonly cmd="$hooks_dir/$hook $*"
	echo "[RUN] ${cmd}"
	${cmd}
done
