#!/usr/bin/env bash

needs_run() {
	if [[ "$1" == *.bash ]]; then
		return 0
	fi
	line=$(head -n 1 "$1")
	if [[ "$line" == *bash* ]]; then
		return 0
	else
		return 1
	fi
}

run_hook() {
	if ! needs_run "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Skipping shfmt/shellcheck %s\n" "$1"
		return 0
	fi

	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Running shfmt %s\n" "$1"
	if ! shfmt -w "$1"; then
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Failing shfmt %s\n" "$1"
		return 1
	fi
	git add "$1"
	[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Running shellcheck %s\n" "$1"
	if shellcheck "$1"; then
		return 0
	else
		[[ -n "$PRE_COMMIT_DEBUG" ]] && printf "Failing shellcheck %s\n" "$1"
		return 1
	fi
}

if run_hook "$1"; then
	exit 0
else
	exit 1
fi
