name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd "$(git rev-parse --show-toplevel)"
          ./.pre-commit-hooks/install
          ./.git/hooks/pre-commit --all
