name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          ./.pre-commit-hooks/pre-commit --all
