name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - uses: pre-commit/action@v2.0.0

  pytest:
    name: pytest ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          version: ${{ matrix.version }}
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: pytest
        run: |
          source .venv/bin/activate
          pytest -nauto
