name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version-file: pyproject.toml
      - run: uv run ruff check .
      - run: uv run ruff format --diff .
