name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: pre-commit/action@v2.0.0
